### ISSUE TITLE
Bulk add members to group

### ISSUE THREAD

**Issue by VicentGJ** [Universidad-Tecnologica-CUJAE/AD-webmanager#15]
Allow adding multiple members to a group in one go.
The LDAP API for this functionality should be working, but the Web interface is not.

**Comment by aleadco** [comment]
Quiero destacar que la interface web funciona, pero no del todo bien como mencioné en #12 . Puedes agregar fácilmente tres, cuatro usuarios o talvez más. El problema está cuando intentas adicionar a un grupo una gran cantidad, hablo de más de 100, ahí es cuando se queda colgado el sistema. Como yo lo interpreto y comenté en #12 es que la solicitud no se completa antes de que finalice el tiempo de espera.

Esto podría resolverse adicionando lo siguiente al proxy inverso de la aplicación, en este caso Nginx

```
proxy_connect_timeout 600; 
proxy_send_timeout 600; 
proxy_read_timeout 600; 
send_timeout 600;
```
