### ISSUE TITLE
[Add] Adicionar datos a la información personal de cada usuario.

### ISSUE THREAD

**Issue by aleadco** [Universidad-Tecnologica-CUJAE/AD-webmanager#17]
Teniendo en cuenta lo planteado en #16 estos datos también deben ser agregados a la información de cada usuario.

También se debe incorporar la variable `o` como medio de verificación de un parámetro que se usa en otros sistemas y que actualmente no se está sincronizando, pero bueno ya eso es del AD, por eso es importante mostrar el dato.

**Importante**: Entre las variables mencionadas en #16 hay una que muestra última fecha en la que fue modificado el usuario. No puede faltar en la información final que usuario fue el que lo modificó. Este dato pudiera aparecer de último, pero es muy importante.

**Comment by carmennavarreteh** [comment]
Para dejarlo claro, esta informacion no va a ir aqui, esto en el otro sistema.   ???? **_Importante: Entre las variables mencionadas en #16 hay una que muestra última fecha en la que fue modificado el usuario. No puede faltar en la información final que usuario fue el que lo modificó. Este dato pudiera aparecer de último, pero es muy importante._**

**Comment by aleadco** [comment]
En la información personal del usuario si debe estar incluida la mayor cantidad de datos que se muestran en el AD incluido el valor del atributo o que muestra la organización a la que pertenece el usuario.

Grupo, Años, Fecha de Creación, Fecha de Creación, departamento, etc... Todo la información que pueda ser posible.

**Comment by VicentGJ** [comment]
En settings.py debe existir una opción para mostrar todos los campos que se consideren necesarios.
