### ISSUE TITLE
Pocos caracteres permitidos en el campo de correo electrónico

### ISSUE THREAD

**Issue by aleadco** [Universidad-Tecnologica-CUJAE/AD-webmanager#33]
Hay que tener en cuenta que la facultad de arquitectura tiene un dominio largo y la cantidad de caracteres permitidos para crear un correo electrónico no es suficiente para sus necesidades.

En el ejemplo siguiente, la dirección de correo mostrada es de 36 caracteres.

![image](https://user-images.githubusercontent.com/35962168/108893396-0eb79080-75df-11eb-8f99-a950f82a5159.png)

**Comment by aleadco** [comment]
De por si los correos electrónicos que se están creando no cumplen con el requisito mínimo establecido. Debo arreglar un usuario en mi dominio tengo el mismo problema.
![image](https://user-images.githubusercontent.com/35962168/108899822-e03db380-75e6-11eb-9eeb-a5dd665a20a2.png)

**Comment by gsoftprop-vicente** [comment]
fixed with #35
