### ISSUE TITLE
Deleting Full Name data breaks user management

### ISSUE THREAD

**Issue by aleadco** [Universidad-Tecnologica-CUJAE/AD-webmanager#45]
When a user is edited, if the Full Name field is deleted, the management from the webmanager is broken.
As a result, none of the user's data is obtained and management is completely lost, it is no longer possible to access the edition or delete the user.

![image](https://user-images.githubusercontent.com/35962168/112560381-76f9bd80-8da9-11eb-86b2-633243643166.png)

**Comment by wrdguezm** [comment]
The full name is now required
