### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by NetBLOKS** [Universidad-Tecnologica-CUJAE/AD-webmanager#50]
Hi,

I just found your project.
It´s very handy, but I am not capable of reading Spanish :-)
I tried implementing the original pages from samba4 manager with limited success.
Is there a chance, this will be translated?

Best regards!

**Comment by VicentGJ** [comment]
Yes, making English version is high priority, and its already in the works, will notify when its ready in this thread. Should be up very soon. Thank you for the feedback!!!

**Comment by VicentGJ** [comment]
Master Branch is already translated to English, please report if you happen to find any remaining issues with the translation. A release will come after some more testing.

**Comment by NetBLOKS** [comment]
Wow, thank you very much!
I´ll dig through the sites, looking for errors.
I´ve found one so far: on the left site:
"Mi Account" should be "My Account"
And the "Type" and "Status" Information are still in Spanish.

Thank you very much again! This is a little life saver for spontaneous work in Samba ADs.

**Comment by VicentGJ** [comment]
Finally had time to fix the final issues with translation!!! Thank you very much for testing and your feedback. Now I'm closing this issue. If you find problems feel free to reopen or create a new one.
