### ISSUE TITLE
[Add] Groups has no possibility to set/edit the email setting

### ISSUE THREAD

**Issue by stdevPavelmc** [Universidad-Tecnologica-CUJAE/AD-webmanager#55]
Hi!

In [MailAD](https://github.com/stdevPavelmc/mailad) we use the email of the group to auto-magically create email distribution groups, so we need a way to set & edit this setting.

More issues to come (I will try to contribute to the fix, but my flask is not so good)

**Note:** _I'm one of the sysadmins of the [SysAdminsdeCuba](https://t.me/sysadmincuba) Telegram group and we are following the development of this software very happily, please evaluate the possibility to join that channel as we can give you valuable feedback and also help on bug squashing and implementing new features, yes, some of the sysadmins are kind of software devs._

**Comment by VicentGJ** [comment]
It will be useful to have a more in depth explanation of what MailAD needs to be configured. What attributes in particular you need to edit for example.

**Comment by stdevPavelmc** [comment]
See [Mailad Automatic alias using ad groups ](https://github.com/stdevPavelmc/mailad/blob/master/Features.md#automatic-alias-using-ad-groups) to details of operations, I will be checking on my dev env to see what other trick we need to implement to make it fully compatible with MailAD

For this feature to work you need to be able to set/edit/unset an email property.

I refreshed my flask knowledge and I think I just make it work, PR on the way as soon I can test it.

BTW: Do you use Ansible? I have crafted a playbook that deploys the service on my local LXC env (any actual debian like distro via SSH) This is a way for devs to rapidly deploy local instances to play (even of local AD DC with dummy pre-loaded users)

**Comment by VicentGJ** [comment]
I merged #60 , now closing the issue.
The ansible thing sounds interesting, please share more details and lets discussed here: #63
