### ISSUE TITLE
[Improve] the instructions to install the software

### ISSUE THREAD

**Issue by stdevPavelmc** [Universidad-Tecnologica-CUJAE/AD-webmanager#56]
Some users at the SysadminsdeCuba community (see #55) are willing to try the software but install instructions are no complete for Debian or Ubuntu (most used distros so far)

So there is a need to improve that, I will send a Pull Request with the fix soon.

**Comment by Joe1962** [comment]
- Dependencias no listadas en la doc (para el caso de Debian-10, template de proxmox):
python-configparser 
python-tz

- Comando para instalar dependencias en Debian-10 (template de proxmox):
apt install python-ldap python-flask python-flaskext.wtf python-dnspython python-wtforms python-configparser python-tz

**Comment by Joe1962** [comment]
Non listed dependencies in the README doc (for Debian-10, proxmox template):
python-configparser
python-tz

- Command for installing dependencies on Debian-10 (proxmox template):
apt install python-ldap python-flask python-flaskext.wtf python-dnspython python-wtforms python-configparser python-tz

**Comment by stdevPavelmc** [comment]
@Joe1962 easy... I'm working on the pull request with the details...

**Comment by stdevPavelmc** [comment]
> Non listed dependencies in the README doc (for Debian-10, proxmox template):
> python-configparser
> python-tz
> 
>     * Command for installing dependencies on Debian-10 (proxmox template):
>       apt install python-ldap python-flask python-flaskext.wtf python-dnspython python-wtforms python-configparser python-tz

You are using python2?

The Pipfile states that they are using python3.9... unless they are ignoring monumentally the pipenv settings...

We need clarification here please...

**Comment by VicentGJ** [comment]
We are using python3.9 at the moment but it is tested to work with python3.6 onwards.
Python2 is not supported.

**Comment by VicentGJ** [comment]
Resolved by #59 , will keep improving the documentation and installation experience down the line, but we have the basics right for now.
