### ISSUE TITLE
[Bug] found while modifying user settings as Administrator

### ISSUE THREAD

**Issue by stdevPavelmc** [Universidad-Tecnologica-CUJAE/AD-webmanager#57]
Using Python 3.9 on a env build from the Pipfile on up to date Ubuntu Linux 20.04

When you try to modify **_any_** of the user property I get a "Data validation failed" see attached image

![Captura de pantalla de 2021-09-07 18-35-05](https://user-images.githubusercontent.com/42220093/132419536-430c5cc0-b1df-4c0c-baa4-06066d0e7827.png)

Setting user password work as expected.

Is this really a bug or I missed something on the config?

**Comment by stdevPavelmc** [comment]
Execution console does not shows anything relevant, see image

![Captura de pantalla de 2021-09-07 18-45-12](https://user-images.githubusercontent.com/42220093/132419938-50121e47-fbac-4793-b7ea-3392bd9fad5d.png)

Is there a extra debug parameter I need to pass to get extra logging data?

**Comment by Joe1962** [comment]
I will just add that simply going in to edit a user, then just clicking "Save changes" will give the same error.

**Comment by stdevPavelmc** [comment]
Also not working against a simple user modifying it's name for example...

**Comment by stdevPavelmc** [comment]
The issue is triggered  by the `form.validate_on_submit()` evaluated to false on users.py, so more debugging lead to the validation error: `{'display_name': ['This field is required.']}`

The field `display_name` is not rendered in the form facing the user as per HTML inspection of the rendered page, its not rendered because it's not part of the form.visible_fields variable.

So... this is the tip of the thread... to much for today, good sleep to everyone.

**Comment by VicentGJ** [comment]
Sorry for the late response, I know about the error and its an easy fix, will be coming up soon.

**Comment by stdevPavelmc** [comment]
Ok, I work on this mostly on nights, will check when you fix it.

**Comment by VicentGJ** [comment]
Pull request #64 should fix the issue but I will not have time to test it until tomorrow.  @stdevPavelmc if you want to test it before, then let mi now if it worked. Will close this issue afterwards
