### ISSUE TITLE
[Add] Imagen del perfil de usuario

### ISSUE THREAD

**Issue by aleadco** [Universidad-Tecnologica-CUJAE/AD-webmanager#9]
Incorporar la imagen del perfil de usuario. Esta puede ser ubicada sobre los botones de edición.

![Anotación 2021-01-04 161358](https://user-images.githubusercontent.com/35962168/103599113-5882d500-4ed2-11eb-98e0-7b6eae59646c.png)

**Comment by gsoftprop-vicente** [comment]
Solved with #48
